
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: {{LOCAL_PATH_REDIS}}
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{NAMESPACE}}
spec:
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack-server:latest
          env:
            - name: REDIS_ARGS
              value: "--appendonly yes"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      nodeSelector:
        kubernetes.io/hostname: {{LOCAL_PATH_NODE}}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{NAMESPACE}}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: redisinsight
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redislabs/redisinsight:latest
        ports:
        - containerPort: 8001
        # env:
        # - name: RIPROXYENABLE
        #   value: "True"
        # - name: RIPROXYPATH
        #   value: "/redis"

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: redisinsight-service
spec:
  selector:
    app: redisinsight
  ports:
    - protocol: TCP
      port: 38081
      targetPort: 8001
  type: LoadBalancer
